<?php

/**
 * @file
 * Contains ns_navigation.module.
 */

use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_theme().
 */
function ns_navigation_theme($existing, $type, $theme, $path) {
  return [
    'ns_intro' => [
      'variables' => [],
    ],
    'ns_about' => [
      'variables' => [],
    ],
  ];
}

/**
 * Implements hook_ENTITY_TYPE_load().
 */
function ns_navigation_views_pre_render($view) {

  if ($view->id() == "ns_references" && ($view->current_display == 'page_2' ||
  $view->current_display == 'page_3')) {

    $tempstore = \Drupal::service('tempstore.private')
      ->get('ns_navigation');

    $current_uri = \Drupal::request()->getRequestUri();
    preg_match('/\?(.*)/', $current_uri, $tokens);

    if ($tokens) {
      $tempstore->set('refs_params', $tokens[1]);
    }
  }

  if ($view->id() == "authors_for" && $view->current_display == 'page_1') {
    $tempstore = \Drupal::service('tempstore.private')
      ->get('ns_navigation');

    $current_uri = \Drupal::request()->getRequestUri();
    preg_match('/authors(.*)/', $current_uri, $tokens);

    if ($tokens) {
      $tempstore->set('authors_params', $tokens[1]);
    }

    if ($tempstore->get('current_ref')) {
      $tempstore->delete('current_ref');
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_load().
 */
function ns_navigation_bibcite_reference_load($entities) {
  if (count($entities) == 1) {
    $ref_id = key($entities);
    $tempstore = \Drupal::service('tempstore.private')
      ->get('ns_navigation');
    $tempstore->set('current_ref', $ref_id);
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ns_navigation_form_bibcite_contributor_delete_form_alter(&$form, $form_state, $form_id) {

  foreach (array_keys($form['actions']) as $action) {
    if ($action != 'preview' && isset($form['actions'][$action]['#type']) &&
    $form['actions'][$action]['#type'] === 'submit') {
      $form['actions'][$action]['#submit'][] = 'del_contrib_redir';
    }
  }

  unset($form['actions']['cancel']);

  $form['custom-cancel'] = [
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#weight' => 100,
    '#submit' => ['del_cancel_redir'],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function ns_navigation_form_bibcite_contributor_edit_form_alter(&$form, $form_state, $form_id) {
  $form['cust_cancel'] = [
    '#id' => 'custom-cancel',
    '#type' => 'submit',
    '#value' => t('Cancel'),
    '#weight' => 100,
    '#submit' => ['del_contrib_redir'],
    '#limit_validation_errors' => [],
  ];
}

/**
 * Implements hook_FORM_alter().
 */
function ns_navigation_form_alter(&$form, &$form_state, $form_id) {

  if (preg_match('/bibcite_reference_(.*)_edit_form/', $form_id)) {
    $ref_id = $form_state->getBuildInfo()['callback_object']->getEntity()->id();

    $form['to_authors'] = [
      '#type' => 'submit',
      '#value' => t('Edit Authors'),
      '#submit' => ['ref_edit_authors'],
    ];

    $form['ref_id'] = [
      '#type' => 'value',
      '#value' => $ref_id,
    ];

    $form['to_results'] = [
      '#type' => 'submit',
      '#value' => t('Results'),
      '#weight' => 100,
      '#submit' => ['del_ref_redir'],
      '#limit_validation_errors' => [],
    ];

  }

  if (preg_match('/bibcite_reference_(.*)_delete_form/', $form_id)) {
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) &&
      $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'del_ref_redir';
      }
    }

    unset($form['actions']['cancel']);

    $form['custom-cancel'] = [
      '#type' => 'submit',
      '#value' => t('Cancel'),
      '#weight' => 100,
      '#submit' => ['del_cancel_redir'],
    ];
  }

  if (array_key_exists('text_keyword__value', $form) && $form_id == "views_exposed_form") {

    $types = [];

    if (array_key_exists('type', $form)) {
      $types = $form['type']['#options'];
    }

    foreach (array_slice($types, 1) as $type) {

      $bib_type = array_search($type, $types);

      $query = \Drupal::entityQuery('bibcite_reference')
        ->condition('type', $bib_type)
        ->execute();

      if (!$query) {
        unset($types[$bib_type]);
      }
    }

    $form['type']['#options'] = $types;
  }

}

/**
 * Handles edit-authors.
 */
function ref_edit_authors(&$form, &$form_state) {
  $ref_id = $form_state->getValue('ref_id');
  $response = new RedirectResponse('/authors-for/' . $ref_id);
  $response->send();
}

/**
 * Handles delete-contributor redirection.
 */
function del_contrib_redir(&$form, &$form_state) {
  $tempstore = \Drupal::service('tempstore.private')
    ->get('ns_navigation');

  $ref_id = $tempstore->get('current_ref') ?
    $tempstore->get('current_ref') : NULL;

  if ($ref_id) {
    $response = new RedirectResponse('/authors-for/' . $ref_id);
    $response->send();
  }
  else {
    $qstring = $tempstore->get('authors_params') ?
      $tempstore->get('authors_params') : '';

    $response = new RedirectResponse('/authors' . $qstring);
    $response->send();
  }
}

/**
 * Handles delete-reference redirection.
 */
function del_ref_redir(&$form, &$form_state) {
  $tempstore = \Drupal::service('tempstore.private')
    ->get('ns_navigation');
  $qstring = $tempstore->get('refs_params') ?
    $tempstore->get('refs_params') : '';

  $response = new RedirectResponse('/references-advanced?' . $qstring);
  $response->send();
}

/**
 * Handles 'back' redirection.
 */
function del_cancel_redir(&$form, &$form_state) {
  $current_uri = \Drupal::request()->getRequestUri();
  $edit_uri = str_replace('delete', 'edit', $current_uri);
  $response = new RedirectResponse($edit_uri);
  $response->send();
}
