ui_override:
  enable_form_override: true
display_override:
  enable_display_override: true
  reference_page_view_mode: default
_core:
  default_config_hash: b2sM7h8Vmyj0QRJFVmpMwsFJJfIL8RVtKFr6UyZvj_Q
