_core:
  default_config_hash: b2sM7h8Vmyj0QRJFVmpMwsFJJfIL8RVtKFr6UyZvj_Q
ui_override:
  enable_form_override: true
display_override:
  reference_page_view_mode: default
  enable_display_override: true
