favicon:
  mimetype: image/png
  path: ''
  url: 'http://default/sites/default/files/favicon_0.png'
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 0
  node_user_picture: 1
logo:
  path: themes/custom/ns_custom/favicon.png
  url: ''
  use_default: 0
schemas:
  bootstrap: 8000
  ns_custom: 8000
navbar_inverse: 0
navbar_position: fixed-top
table: ''
