favicon:
  mimetype: image/png
  path: 'public://favicon_0.png'
  url: 'http://192.168.99.100:3089/themes/contrib/bootstrap/favicon.ico'
  use_default: 0
features:
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
  node_user_picture: 1
logo:
  path: ''
  url: ''
  use_default: 0
schemas:
  bootstrap: 8000
  ns_custom: 8000
table: ''
